### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by colelamers** [tcvang229/cs316Final#1]
I know Kevin Xiong and I noticed he worked together with you on this. I'm currently in CS 256 and will have 316 in the summer. 

I just wanted to ask why you are using XML files and how you guys learned to use it? Will that something we'll need to use in the course?

**Comment by xJunit123x** [comment]
The XML file in that project is actually just the file that gets created when building a User Interface with JavaFX and exporting it, so we didn’t actually physically “write” any of that code, so to speak. In around the second half of 316 we learn how to make some basic user interfaces with JavaFX using a program called SceneBuilder, which just has a drag-and-drop feature for adding in buttons and textboxes and layouts. There’ll be some labs and assignments that will require you to use it, but for the final project you won’t be required to use it if you don’t want to.  From: Cole LamersSent: Tuesday, April 14, 2020 11:07 AMTo: tcvang229/cs316FinalCc: SubscribedSubject: [tcvang229/cs316Final] Question about code (#1) I know Kevin Xiong and I noticed he worked together with you on this. I'm currently in CS 256 and will have 316 in the summer.I just wanted to ask why you are using XML files and how you guys learned to use it? Will that something we'll need to use in the course?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by colelamers** [comment]
I'm glad to know it isn't something too difficult then. I appreciate you replying so fast too! Thanks a bunch!
